# -*- coding: utf-8 -*-
"""verificar_pedidos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ks38McYDfULD6m5gV5ScKVnTQZiQc8nW
"""



"""Para implementar esta mejora, vamos a crear una función llamada verificar_pedidos que verificará si los pedidos confirmados a futuro provocan que el stock previsto caiga por debajo del stock de seguridad en algún momento durante el periodo de planificación. Si esto ocurre, se añadirá el artículo a la lista de productos que deben planificarse."""

import pandas as pd
from datetime import datetime, timedelta

def verificar_pedidos(productos, archivo_pedidos, fecha_dataset, dias_planificacion):
    """
    Verifica si los pedidos confirmados a futuro provocan que el stock previsto
    caiga por debajo del stock de seguridad en algún momento durante el periodo de planificación.

    :param productos: Lista de productos con demanda media y stock inicial calculados.
    :param fecha_dataset: Fecha del dataset (datetime).
    :param dias_planificacion: Número de días de planificación.
    :return: Lista de productos que deben planificarse adicionalmente debido a pedidos.
    """
    try:
        # Generar el nombre del archivo de pedidos
        fecha_dataset_str = fecha_dataset.strftime('%d-%m-%y')
        archivo_pedidos = f'/content/Pedidos pendientes {fecha_dataset_str}.csv'

        # Verificar si el archivo existe
        if not os.path.exists(archivo_pedidos):
            logger.warning(f"No se encontró el archivo de pedidos: {archivo_pedidos}")
            return []

        # Leer el archivo de pedidos
        df_pedidos = pd.read_csv(archivo_pedidos, sep=';', encoding='latin1')

        # Convertir las columnas de fechas a datetime
        fechas_pedidos = [col for col in df_pedidos.columns if col.startswith('09') or col.startswith('10') or col.startswith('11') or col.startswith('12') or col.startswith('13') or col.startswith('14') or col.startswith('15') or col.startswith('16') or col.startswith('17') or col.startswith('18') or col.startswith('19') or col.startswith('20') or col.startswith('21') or col.startswith('22') or col.startswith('23') or col.startswith('24') or col.startswith('25') or col.startswith('26') or col.startswith('27') or col.startswith('28') or col.startswith('29') or col.startswith('30') or col.startswith('31')]
        df_pedidos[fechas_pedidos] = df_pedidos[fechas_pedidos].apply(pd.to_numeric, errors='coerce').fillna(0)

        # Convertir fechas a datetime
        df_pedidos['COD_ART'] = df_pedidos['COD_ART'].astype(str)

        # Lista de productos que deben planificarse adicionalmente
        productos_a_planificar = []

        # Recorrer cada producto
        for producto in productos:
            if producto.demanda_media <= 0:
                continue  # No se considera si no hay demanda media

            # Obtener los pedidos para este producto
            pedidos_producto = df_pedidos[df_pedidos['COD_ART'] == producto.cod_art]
            if pedidos_producto.empty:
                continue  # No hay pedidos para este producto

            # Inicializar el stock previsto
            stock_previsto = producto.stock_inicial
            stock_seguridad = producto.demanda_media * 3

            # Recorrer día a día
            for i in range(dias_planificacion):
                fecha_actual = fecha_dataset + timedelta(days=i)
                fecha_str = fecha_actual.strftime('%d/%m/%Y')

                # Restar la demanda media
                stock_previsto -= producto.demanda_media

                # Sumar la OF si la fecha es igual o superior a la del dataset
                if hasattr(producto, 'primera_of') and producto.primera_of != '(en blanco)':
                    of_date = datetime.strptime(producto.primera_of, '%d/%m/%Y')
                    if of_date <= fecha_actual:
                        stock_previsto += producto.of

                # Restar los pedidos del día
                if fecha_str in df_pedidos.columns:
                    pedido_dia = pedidos_producto[fecha_str].values[0]
                    if pd.notna(pedido_dia):
                        stock_previsto -= abs(pedido_dia)  # Los pedidos son negativos en el archivo

                # Verificar si el stock previsto es menor que el stock de seguridad
                if stock_previsto < stock_seguridad:
                    logger.warning(f"El día {fecha_str}, el stock de seguridad ha sido sobrepasado para el producto {producto.cod_art}.")

                    # Calcular la cantidad a fabricar
                    dias_faltantes = dias_planificacion - i
                    cantidad_a_fabricar = producto.demanda_media * min(dias_faltantes + 7, dias_planificacion) + abs(pedido_dia)

                    # Añadir el producto a la lista de productos a planificar
                    producto.cajas_a_producir = cantidad_a_fabricar
                    productos_a_planificar.append(producto)
                    break  # Solo necesitamos detectar la primera vez que se sobrepasa el stock de seguridad

        logger.info(f"Se han identificado {len(productos_a_planificar)} productos adicionales para planificar debido a pedidos.")
        return productos_a_planificar

    except Exception as e:
        logger.error(f"Error verificando pedidos: {str(e)}")
        return []

"""Explicación de la Función
Lectura del Archivo de Pedidos:

Se lee el archivo CSV de pedidos pendientes.

Las columnas de fechas se convierten a valores numéricos (los pedidos son negativos en el archivo).

Recorrido de Productos:

Para cada producto, se inicializa el stock previsto con el stock inicial.

Se calcula el stock de seguridad como demanda_media * 3.

Simulación Día a Día:

Se simula el stock previsto restando la demanda media y sumando las OF si corresponde.

Se restan los pedidos del día actual si existen.

Verificación de Stock de Seguridad:

Si el stock previsto cae por debajo del stock de seguridad, se registra una advertencia y se calcula la cantidad a fabricar.

La cantidad a fabricar asegura cubrir los pedidos desproporcionados y mantener el stock durante al menos 7 días después del periodo de planificación.

Productos a Planificar:

Los productos que requieren planificación adicional se añaden a la lista productos_a_planificar.

Integración en el Flujo Principal
La función verificar_pedidos se integra en el flujo principal después de calcular la demanda media y antes de aplicar el método Simplex. Aquí está el fragmento relevante:
"""

def main():
    try:
        logger.info("Iniciando planificación de producción...")

        # (Código existente para leer parámetros y dataset)

        # 1. Leer dataset y calcular fórmulas
        productos = leer_dataset('/content/Dataset 09-01-25.csv')
        if not productos:
            raise ValueError("Error al leer el dataset")

        productos_validos, horas_disponibles = calcular_formulas(
            productos=productos,
            fecha_inicio=fecha_planificacion,
            fecha_dataset=fecha_dataset,
            dias_planificacion=dias_planificacion,
            dias_no_habiles=dias_no_habiles,
            horas_mantenimiento=horas_mantenimiento
        )

        if not productos_validos:
            raise ValueError("Error en los cálculos")

        # 2. Verificar pedidos pendientes
        productos_a_planificar_adicionales = verificar_pedidos(
            productos=productos,
            fecha_dataset=fecha_dataset_dt,
            dias_planificacion=dias_planificacion
        )

        # Combinar productos válidos con los adicionales
        productos_a_planificar = productos_validos + productos_a_planificar_adicionales

        # 3. Aplicar Simplex
        productos_optimizados = aplicar_simplex(
            productos_validos=productos_a_planificar,
            horas_disponibles=horas_disponibles,
            dias_planificacion=dias_planificacion,
            dias_cobertura_base=dias_cobertura_base
        )

        if not productos_optimizados:
            raise ValueError("Error en la optimización")

        # (Resto del código para ordenar y exportar resultados)

    except Exception as e:
        logger.error(f"Error en ejecución: {str(e)}")
        return None

"""Resultado
Productos Adicionales:

Los productos que requieren planificación adicional debido a pedidos desproporcionados se añaden a la lista de productos a planificar.

Estos productos se incluyen en la optimización con el método Simplex.

Advertencias:

Si el stock previsto cae por debajo del stock de seguridad, se registra una advertencia en el log.

Ejemplo de Salida
Si el producto 400121 tiene un pedido desproporcionado el día 10/01/2025, el log mostrará:

WARNING: El día 10/01/2025, el stock de seguridad ha sido sobrepasado para el producto 400121.

Y el producto se añadirá a la lista de productos a planificar.

Con esta mejora, el sistema ahora tiene en cuenta los pedidos confirmados a futuro, evitando roturas de stock y asegurando una planificación más robusta. ¡Espero que esta implementación sea útil! 😊
"""